apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: goserver
  newName: ivanaugustineli/gitopssulavan
  newTag: 0336f4843819f8aa6e97df66800f1cbd1b03f548
