apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: goserver
  newName: ivanaugustineli/gitopssulavan
  newTag: 5ec7b24127a1ba97c2e9d3ec10a25bcf008f2236
